### ISSUE TITLE
Failing to locate libintl.h results to runtime issues for users if NLS is enabled

### ISSUE THREAD

**Issue by diizzyy** [rpm-software-management/popt#32]
If the configure script doesn't detect libintl.h it should fail not continue, this leads to various issues with users of libpopt as it doesn't work as intended. 

Reported here:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=247529
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=247529#c9

**Comment by pmatilai** [comment]
I kinda disagree on stopping at configure, but if it proceeds it should also work instead of segfaulting. Clearly there's a bug or a bunch in there, the if-fubar around these matters seems convoluted and strange, so not a big surprise. Thanks for reporting!

That this appears as a regression from 1.16 on FreeBSD is a bit surprising though. Hmm. It's segfaulting in poptPrintUsage() which suggests commit 83302258da3d54257dffb01297131065c683aa90 is to blame.

**Comment by cheng362432** [comment]
https://github.com/rpm-software-management/popt/commit/7219e1ddc1e8606dda18c1105df0d45d8e8e0e09

Does this commit fix this problem?

reference：https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=247529#c10

**Comment by diizzyy** [comment]
No, you still need to make sure that libintl.h is available
